# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Docker@2
  inputs:
    command: 'build'
    containerRegistry: 'quayServiceConnection'
    repository: 'p1987br/space-shuttle'
    Dockerfile: '**/Dockerfile'
    tags: latest

- script: |
    docker images
  displayName: 'Run a docker'

- script: |
    docker run --entrypoint ./build-app.sh quay.io/p1987br/space-shuttle
  displayName: 'Run a docker'

- task: Docker@2
  inputs:
    containerRegistry: 'quayServiceConnection'
    command: 'start'
    arguments: '-it --entrypoint ./build-app.sh'
    container: 'quay.io/p1987br/space-shuttle:latest'

- task: Docker@2
  inputs:
    containerRegistry: 'quayServiceConnection'
    repository: 'p1987br/space-shuttle'
    command: 'push'
    tags: latest

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
